### ISSUE TITLE
Asking about slide info on Feb,16,2023 conference

### ISSUE THREAD

**Issue by HiImDarwin** [Wireless-Innovation-Forum/6-GHz-AFC#28]
Hi im Darwin,
    I'm not sure if I should ask on Github or somewhere. So if I need to ask somewhere else. feel free to let me know.
I watch the "Introduction to AFC System Lab Testings" on Youtube and have one question.
On the part of Masoud Olfat talk about " AFC Traceability Matrix and SUT Testing Framework".
He got a  pic of excel which is talking about AFC Traceability Matrix (3rd page of his part).
![image](https://user-images.githubusercontent.com/53218645/220862430-c55bbfe5-cbc9-4e0d-8299-cda762ca2a25.png)
I check the Test Vector excel which I download from WFA and can't find that part.
I wonder where can I got the sheet of AFC Traceability Matrix or that is not open.
No matter what answer it is, thanks for your reply.

**Comment by AEgbert** [comment]
The AFC Traceability Matrix is maintained by the Wireless Innovation Forum, which is why you didn't find it in the WFA download. You can access the most recently published version of the AFC Traceability Matrix under the "6GHz Traceability Matrix" link here: https://6ghz.wirelessinnovation.org/policies-and-procedures
