### ISSUE TITLE
AFC output validation with response mask for Testvector 1 (AFCS.FSP.1_mask.json)

### ISSUE THREAD

**Issue by sbasu07** [Wireless-Innovation-Forum/6-GHz-AFC#39]
Hi,
I am trying to implement the functionality of an AFC system. As a first step, I have implemented freespace pathloss model and I am trying to match the response output for test vector 1 in the AFC System (SUT) Compliance Test Vectors v1.2 document (Incumbent proximity <=30m)
I have followed the these steps:
1.	Gathered nearest incumbent data from ULS. I found 3 incumbents in a distance of 9.08m. 
[Reference: https://github.com/Wi-FiTestSuite/6GHz-AFC/blob/17656cc709795a704bbbd7eeda5bfbb67b2560ef/ULS_database/FCC/weekly/l_micro_211024_modified_PA.zip ]
2.	I am using the following equation to calculate the maximum safe EIRP (R2-AIP-16 in WINNF-TS-1014-V1.3.0)
![image](https://github.com/Wireless-Innovation-Forum/6-GHz-AFC/assets/45750317/e4825d2b-b9af-4ad3-8c95-397008c8d6c9)

=>	PSPD, Tx = I/NRx, Est +N + LPropagation, Rx + LBEL + LFS, Feeder - GRx, Effective 
And, PSPD, Tx = Transmit EIRP of SPD 
I am trying to find the maximum EIRP of SPD by using the maximum I/N ratio at Receiver (-6 dB)

Observing the incumbent data from FR.dat file I found that incumbent is present in 9.07m distance from the SPD, operating in both channel number 15 and 143 (in Global operating class 134). But the response mask shows 26 dB difference in maximum EIRP value.
The following is a snapshot of the response mask in AFCS.FSP.1_mask.json file:

![image](https://github.com/Wireless-Innovation-Forum/6-GHz-AFC/assets/45750317/d847d898-5531-4a1c-8fda-29e552f54c1b)

What is the parameter that is causing such a huge difference in the EIRP values in freespace testcase?
Is there any other parameter to be considered than those mentioned in equation?

**Comment by AEgbert** [comment]
Taking a look at the frequency-based results for FSP.1, I see that channel 15's restriction is related to a -11.4 dBm/MHz upper bound between 5930-5990 MHz (lines 18-27 of `AFCS.FSP.1_mask.json`). Assuming that the channel power will be uniform across the AFC device's 160 MHz bandwidth (no more than -11.4 dBm/MHz throughout the entire channel), then integrating this power density over 160 MHz leads to a channel EIRP of 10.64 dBm (-11.4 dBm/MHz -> 0.0724 mW/MHz * 160 MHz = 11.591 mW -> 10.64 dBm). This matches the mask's 10.7 dBm EIRP limit for channel 15.

Meanwhile, the primary limit for channel 143 is related to the -38 dBm/MHz upper bound between 6640-6650 MHz (lines 118-127 of `AFCS.FSP.1_mask.json`). Following a similar process, a -38 dBm/MHz limit over 160 MHz leads to a channel EIRP of -15.96 dBm. This matches the mask's -16 dBm EIRP limit for channel 143.

While I've not delved into the creation of the frequency-based response limits and why different PSD limits exist for the frequency ranges of those two channels in the first place, my guess is that at least part of the PSD limit difference is due to the incumbent being protected operating over differently sized bandwidths for the two channels, which leads to different noise levels `N` to which the I/N threshold is applied. (See WINNF-TS-1014 R2-AIP-02, which specifies a value of `N` in dBm/MHz, which needs to be scaled to the bandwidth under consideration before its use in R2-AIP-16).

Does this address your question about the difference in max EIRP for channels 15 and 143? If not, I can try to find someone who may be able to provide some more insight into how the frequency-based availability was derived.

**Comment by sbasu07** [comment]
Thank you for your response. I have taken into account receiver bandwidths for noise and effective receiver gain as well, but I am unable to match the response.  It will be helpful if you could provide an example derivation for channels 15 and 143 for the test vector AFC.FSP1 or any other test vector with the incumbent details (callsign, location no, antenna no, gain, frequency, distance etc.) used for the calculation. It will be really helpful in validating my method of implementing AFC functionalities according to the WINNF-TS-1014-V1.3.0 document.

**Comment by AEgbert** [comment]
Thanks for the feedback. Your question is similar to what is raised in #40, so you may wish to check there for more info. I've also passed on the request for an example derivation for one of the test vectors that would include the information you've asked for. We hope to provide an example derivation soon, and I'll update this issue as I have more information.

In the meantime, I've been advised that AFCS.FSP1 is one of the more complicated test vectors, as the AFC device's location uncertainty footprint overlaps the location of a relevant incumbent. Within this footprint, the slant distance and effective incumbent RX antenna gain in the direction of the AFC device can vary significantly. You might wish to try again with a test vector that does not have an overlapping footprint, such as FSP.30.

**Comment by sbasu07** [comment]
Hi @AEgbert could you provide the effective gain calculation for FSP30 test vector? I have found the following values of the parameters following according to R2-AIP-36,
Incumbent RX location : (30.1225, -101.0965)
SPD location (grid point in the uncertainty region for highest interference) = (30.0880, -101.1038)

according to R2-AIP-36 a.i: 
AZ_bearing_to_eval: 190.48930055202055
AZ_boresight: 190.28403498874562
theta_AZ_disc:  0.20526556327493495

according to R2-AIP-36 a.ii :
Receiver ground elevation : 596.2 m (AMSL)
Transmitter ground elevation  608.4 m (AMSL)
RX antenna height to centre RAAT= 69.5 m
TX antenna height  to centre RAAT= 27.1 m
H_FS_RX : 665.7 m
H_FS_TX : 635.5 m
dFSTx-FSRx: 39241.5051147923 m
r_earth= 8500*1000 m
Theta EL Disc : -0.1763511052152199

according to R2-AIP-36 a.iii :
Evalpoint (SPD) ground elevation : 515.38 m (AMSL)
Height of SPD antenna = 110 m 
H_EP : 625.38 m
dEP-FSRx = 3883.181431390412 m
Phi : -0.607952143968807

according to R2-AIP-36 b:
gamma: 0.47792388005725195

according to R2-AIP-36 c:
G_AZ Disc -1.3467248509684282 (from R2-AIP-07 b.ii.3)

according to R2-AIP-36 d:
G_EL Disc: -0.2 (from manufacturer RPE VV)
beta :  -0.007532807691660253

according to R2-AIP-36 e:
wA is 0.1844480403417645
wE is 0.8155519596582355
antenna diameter = 2.4384 m
category = 'A'
Effective RX gain 41.188488848427674 dB
Gain reduction -0.4115111515723271 dB

slant Distance between Receiver and SPD is 3883.39 m
frequency: 5974.85 MHz
pathloss 119.75 dB (Free space path loss is chosen. ITM was 116.334 dB)

Would you help me out with a few questions regarding this -
Q.1 Could you let me know where did my calculation method differ from you? 
Q2. How does the antenna polarization play role in R2-AIP-36 ? Is it the same procedure for all polarization 'H', 'V' and 'S'?
Q3. What value of theta_Disc is to be considered for default RPE calculation (R2-AIP-07 b.ii)? Is it the same gamma mentioned in    R2-AIP-36, or only theta_AZ_disc?

**Comment by AEgbert** [comment]
> Q.1 Could you let me know where did my calculation method differ from you?

Nothing in particular stands out to me regarding your calculations. Are you arriving at a significantly different result than FSP-30 provides? If you're referencing values from #40, my estimates have neglected the SPD uncertainty region for simplicity instead of identifying the evaluation grid point with the most interference.

Please note that I am not an AFC system provider and do not have access to any existing AFC systems, so my estimates have been manually calculated and may be subject to error. None of my responses should be interpreted as official AFC system calculations or results.

> Q2. How does the antenna polarization play role in R2-AIP-36 ? Is it the same procedure for all polarization 'H', 'V' and 'S'?

Consideration of antenna polarization is handled via R2-AIP-09-b.

> Q3. What value of theta_Disc is to be considered for default RPE calculation (R2-AIP-07 b.ii)? Is it the same gamma mentioned in R2-AIP-36, or only theta_AZ_disc?

Theta<sub>Disc</sub> is defined in Section 3.3 of TS-1014. Based on the definition in Section 3.3 and my understanding of gamma from R2-AIP-36, I believe these are these same value.

**Comment by sbasu07** [comment]
Hi, thank you for the clarification, I wanted to confirm my understanding about the effective receiver gain calculation method. I am arriving quite close to FSP-30 now.
Thanks.
